"""Tests for scripts/check_version_consistency.py (#911).

保護機構は不発でも green になるため、本テストは **違反を注入して exit code の
生値を観測する** 形で書く。正常系だけを見て「ガードがある」と判断しない。
"""

from __future__ import annotations

import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = REPO_ROOT / "scripts"

_spec = importlib.util.spec_from_file_location(
    "check_version_consistency", SCRIPTS_DIR / "check_version_consistency.py"
)
assert _spec is not None and _spec.loader is not None
cvc = importlib.util.module_from_spec(_spec)
# @dataclass は解決時に sys.modules[cls.__module__] を引くため、exec_module の前に
# 登録しておかないと AttributeError になる。
sys.modules[_spec.name] = cvc
_spec.loader.exec_module(cvc)


def _write_synthetic_repo(root: Path, version: str = "1.2.3") -> None:
    """全バージョン保持箇所が `version` で一致した合成 repo を作る。"""
    (root / "gui" / "src-tauri").mkdir(parents=True, exist_ok=True)

    (root / "pyproject.toml").write_text(
        f'[project]\nname = "allaganeye"\nversion = "{version}"\n', encoding="utf-8"
    )
    (root / "gui" / "src-tauri" / "Cargo.toml").write_text(
        f'[package]\nname = "allaganeye-gui"\nversion = "{version}"\nedition = "2021"\n',
        encoding="utf-8",
    )
    (root / "gui" / "package.json").write_text(
        json.dumps({"name": "allaganeye-gui", "version": version}), encoding="utf-8"
    )
    (root / "gui" / "package-lock.json").write_text(
        json.dumps(
            {
                "name": "allaganeye-gui",
                "version": version,
                "packages": {"": {"name": "allaganeye-gui", "version": version}},
            }
        ),
        encoding="utf-8",
    )
    (root / "gui" / "src-tauri" / "tauri.conf.json").write_text(
        json.dumps({"productName": "allaganeye-gui", "version": version}),
        encoding="utf-8",
    )
    # Cargo.lock は実物の構造を再現する。落とし穴が 2 つあるため:
    #   1. root 直下の `version = 4` は lockfile フォーマット版であってリリース
    #      バージョンではない
    #   2. 依存クレートも `[[package]]` として同じ形で並ぶ (ここでは serde 1.0.0)
    # どちらも拾ってはいけない。
    (root / "gui" / "src-tauri" / "Cargo.lock").write_text(
        "# This file is automatically @generated by Cargo.\n"
        "version = 4\n"
        "\n"
        '[[package]]\nname = "serde"\nversion = "1.0.0"\n'
        'source = "registry+https://github.com/rust-lang/crates.io-index"\n'
        "\n"
        f'[[package]]\nname = "allaganeye-gui"\nversion = "{version}"\n'
        'dependencies = [\n "serde",\n]\n',
        encoding="utf-8",
    )


def _error_lines(captured: str) -> list[str]:
    """`::error::` 注釈行だけを抜き出す。

    スクリプトは常に全箇所の一覧を stdout に出すため、出力全体に対して path の
    存在を assert すると「ガードが発火していなくても通る」vacuous green になる。
    発火の証拠は `::error::` 行に限定して観測する。
    """
    return [line for line in captured.splitlines() if line.startswith("::error::")]


def _versions_in(captured: str, path: str) -> list[str]:
    """一覧行 (`<path> (<field>): <version>`) から `path` 由来の値だけを抜き出す。"""
    return [
        line.rsplit(": ", 1)[1]
        for line in captured.splitlines()
        if line.startswith(f"{path} (")
    ]


def _set_version_at(root: Path, location: Any, version: str) -> None:
    """`location` が指す箇所のバージョンだけを差し替える。

    `cvc` は importlib で動的ロードした module なので `VersionLocation` を静的型と
    しては参照できない。型は `Any` にし、実体の検査は実行時の `isinstance` で行う。
    """
    assert isinstance(location, cvc.VersionLocation)
    path = root / location.path
    if location.fmt == "json":
        data = json.loads(path.read_text(encoding="utf-8"))
        for keys in location.keys:
            node = data
            for key in keys[:-1]:
                node = node[key]
            node[keys[-1]] = version
        path.write_text(json.dumps(data), encoding="utf-8")
    elif location.select is not None:
        # Cargo.lock は該当 [[package]] ブロックの version 行だけを差し替える
        # (root の `version = 4` や依存クレートの version を巻き込まない)。
        _, field, expected = location.select
        text = path.read_text(encoding="utf-8")
        text, replaced = re.subn(
            rf'(^{field} = "{re.escape(expected)}"\n)version = ".*"$',
            rf'\g<1>version = "{version}"',
            text,
            flags=re.M,
        )
        assert replaced == 1, (
            f"{location.path}: 差し替え対象が {replaced} 件 (1 件のはず)"
        )
        path.write_text(text, encoding="utf-8")
    else:
        text = path.read_text(encoding="utf-8")
        path.write_text(
            re.sub(r'^version = ".*"$', f'version = "{version}"', text, flags=re.M),
            encoding="utf-8",
        )


# --------------------------------------------------------------------------
# 正常系
# --------------------------------------------------------------------------


def test_all_locations_agree_returns_0(tmp_path: Path) -> None:
    _write_synthetic_repo(tmp_path, "1.2.3")
    assert cvc.main(["--repo-root", str(tmp_path)]) == 0


def test_matching_tag_returns_0(tmp_path: Path) -> None:
    _write_synthetic_repo(tmp_path, "1.2.3")
    assert cvc.main(["--repo-root", str(tmp_path), "--tag", "v1.2.3"]) == 0


# --------------------------------------------------------------------------
# 発火実証: 箇所ごとに 1 つずつズラす
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "location", cvc.VERSION_LOCATIONS, ids=[loc.path for loc in cvc.VERSION_LOCATIONS]
)
def test_each_location_mismatch_returns_1(
    tmp_path: Path, location: Any, capsys: pytest.CaptureFixture[str]
) -> None:
    """全箇所のいずれか 1 つがズレただけで exit 1 になること (箇所ごとの発火実証)。

    `::error::` 行のうち **注入した値 9.9.9 を報告している行** に当該 path が
    含まれることまで検査する (単に path が出力に現れるだけでは発火の証拠にならない)。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")
    _set_version_at(tmp_path, location, "9.9.9")

    rc = cvc.main(["--repo-root", str(tmp_path)])
    errors = _error_lines(capsys.readouterr().out)

    assert rc == 1
    assert isinstance(location, cvc.VersionLocation)
    offending = [line for line in errors if '"9.9.9"' in line]
    assert offending, f"注入した 9.9.9 を報告する ::error:: 行がない: {errors}"
    assert all(location.path in line for line in offending)


def test_package_lock_nested_field_mismatch_returns_1(tmp_path: Path) -> None:
    """package-lock.json の `packages[""].version` だけのズレも検知すること。

    npm は root `version` と `packages[""].version` の双方を持つため、片方だけが
    古びる drift が実在する。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")
    lock = tmp_path / "gui" / "package-lock.json"
    data = json.loads(lock.read_text(encoding="utf-8"))
    data["packages"][""]["version"] = "9.9.9"
    lock.write_text(json.dumps(data), encoding="utf-8")

    assert cvc.main(["--repo-root", str(tmp_path)]) == 1


def test_cargo_lock_ignores_lockfile_format_and_dependency_versions(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Cargo.lock は allaganeye-gui の `[[package]]` だけを見ること。

    素朴に「`version = ` 行」を拾う実装だと、root の lockfile フォーマット版
    (`version = 4`) や依存クレートの version (serde 1.0.0) を掴んでしまい、
    バンプしていないのに毎回 fail する / あるいは無関係な値で比較する。
    合成 repo は両方を仕込んであるので、ここが 0 で通ること自体が証拠になる。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")

    assert cvc.main(["--repo-root", str(tmp_path)]) == 0

    out = capsys.readouterr().out
    assert "gui/src-tauri/Cargo.lock" in out
    assert "4" not in _versions_in(out, "gui/src-tauri/Cargo.lock")
    assert _versions_in(out, "gui/src-tauri/Cargo.lock") == ["1.2.3"]


def test_cargo_lock_missing_package_entry_returns_2(tmp_path: Path) -> None:
    """パッケージ名が変わって `[[package]]` を特定できないときは exit 2 に倒すこと。

    「見つからないので検査しない」を 0 で通すと、ガードが無いより有害になる。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")
    lock = tmp_path / "gui" / "src-tauri" / "Cargo.lock"
    lock.write_text(
        lock.read_text(encoding="utf-8").replace(
            'name = "allaganeye-gui"', 'name = "allaganeye-gui-renamed"'
        ),
        encoding="utf-8",
    )

    assert cvc.main(["--repo-root", str(tmp_path)]) == 2


def test_tag_mismatch_returns_1(tmp_path: Path) -> None:
    """全箇所が一致していても tag とズレていれば fail すること。"""
    _write_synthetic_repo(tmp_path, "1.2.3")
    assert cvc.main(["--repo-root", str(tmp_path), "--tag", "v9.9.9"]) == 1


def test_mismatch_reports_every_offending_location(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """複数箇所がズレたとき、最初の 1 件で打ち切らず全件報告すること。"""
    _write_synthetic_repo(tmp_path, "1.2.3")
    _set_version_at(tmp_path, cvc.VERSION_LOCATIONS[1], "9.9.9")
    _set_version_at(tmp_path, cvc.VERSION_LOCATIONS[2], "8.8.8")

    rc = cvc.main(["--repo-root", str(tmp_path)])
    errors = _error_lines(capsys.readouterr().out)

    assert rc == 1
    assert any(
        '"9.9.9"' in line and cvc.VERSION_LOCATIONS[1].path in line for line in errors
    )
    assert any(
        '"8.8.8"' in line and cvc.VERSION_LOCATIONS[2].path in line for line in errors
    )


# --------------------------------------------------------------------------
# 構造エラー (検査の自己崩壊を green で通さない)
# --------------------------------------------------------------------------


def test_missing_file_returns_2(tmp_path: Path) -> None:
    _write_synthetic_repo(tmp_path, "1.2.3")
    (tmp_path / cvc.VERSION_LOCATIONS[0].path).unlink()
    assert cvc.main(["--repo-root", str(tmp_path)]) == 2


def test_missing_field_returns_2(tmp_path: Path) -> None:
    _write_synthetic_repo(tmp_path, "1.2.3")
    pkg = tmp_path / "gui" / "package.json"
    pkg.write_text(json.dumps({"name": "allaganeye-gui"}), encoding="utf-8")
    assert cvc.main(["--repo-root", str(tmp_path)]) == 2


def test_unparseable_file_returns_2(tmp_path: Path) -> None:
    _write_synthetic_repo(tmp_path, "1.2.3")
    (tmp_path / "gui" / "package.json").write_text("{ not json", encoding="utf-8")
    assert cvc.main(["--repo-root", str(tmp_path)]) == 2


# --------------------------------------------------------------------------
# --list-paths (バンプ時の stage 対象を機械的に得る)
# --------------------------------------------------------------------------


def test_list_paths_emits_deduped_paths(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """`git add --` に直接渡せる形 (1 行 1 path、重複なし) で出ること。

    `package-lock.json` は 2 フィールドを持つが stage 単位はファイルなので、
    path としては 1 個に畳まれていなければならない。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")

    rc = cvc.main(["--repo-root", str(tmp_path), "--list-paths"])
    lines = capsys.readouterr().out.splitlines()

    assert rc == 0
    assert lines == list(dict.fromkeys(loc.path for loc in cvc.VERSION_LOCATIONS))
    assert len(lines) == len(set(lines))


def test_list_paths_emits_lf_only() -> None:
    """改行が LF 固定であること (Windows の CRLF を出さない)。

    出力は `git add -- $(python ... --list-paths)` で機械消費される。Windows の
    text-mode stdout は "\\n" を CRLF へ変換するが、bash の既定 IFS は "\\r" を
    区切りに含めないため path 末尾に "\\r" が残り `git add` が exit 128 で落ちる
    (empirical-prompt-tuning iteration 5 の実測)。

    `capsys` は改行変換を挟まないので捕捉できない。実際に subprocess で起動して
    **生バイト列**を見る必要がある。
    """
    result = subprocess.run(
        [
            sys.executable,
            str(SCRIPTS_DIR / "check_version_consistency.py"),
            "--list-paths",
        ],
        capture_output=True,
        check=True,
    )
    assert b"\r" not in result.stdout
    assert result.stdout.decode("utf-8").splitlines() == list(
        dict.fromkeys(location.path for location in cvc.VERSION_LOCATIONS)
    )


def test_list_paths_does_not_read_files(tmp_path: Path) -> None:
    """バージョン値を読まずに path だけ返すこと。

    バンプ途中 (= まだ全箇所が一致していない状態) で stage 対象を得るための
    mode なので、不一致や欠損があっても path 一覧は返せなければ意味がない。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")
    (tmp_path / cvc.VERSION_LOCATIONS[0].path).unlink()

    assert cvc.main(["--repo-root", str(tmp_path), "--list-paths"]) == 0


# --------------------------------------------------------------------------
# 実 repo に対する pin test / doc 突合
# --------------------------------------------------------------------------


def test_real_repo_versions_are_consistent() -> None:
    """現在の repo の全バージョン保持箇所が一致していること (恒久 gate)。"""
    assert cvc.main(["--repo-root", str(REPO_ROOT)]) == 0


def test_versioning_doc_lists_exactly_the_guarded_locations() -> None:
    """`docs/versioning.md` の一覧と `VERSION_LOCATIONS` が集合一致すること。

    #911 の root cause は「doc が 3 箇所と宣言している間に実態が 5 箇所へ増えていた」
    こと。doc 側の一覧が silent に古びる経路を塞ぐ。
    """
    doc = (REPO_ROOT / "docs" / "versioning.md").read_text(encoding="utf-8")
    section = doc.split("## バージョン管理場所", 1)[1].split("\n## ", 1)[0]

    documented = {
        m.group(1)
        for line in section.splitlines()
        if line.startswith("| `")
        if (m := re.match(r"\|\s*`([^`]+)`", line))
    }
    guarded = {loc.path for loc in cvc.VERSION_LOCATIONS}

    assert documented == guarded, (
        f"docs/versioning.md と VERSION_LOCATIONS が乖離: "
        f"doc のみ={documented - guarded} / script のみ={guarded - documented}"
    )
