"""Tests for scripts/check_version_consistency.py (#911).

保護機構は不発でも green になるため、本テストは **違反を注入して exit code の
生値を観測する** 形で書く。正常系だけを見て「ガードがある」と判断しない。
"""

from __future__ import annotations

import importlib.util
import json
import re
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = REPO_ROOT / "scripts"

_spec = importlib.util.spec_from_file_location(
    "check_version_consistency", SCRIPTS_DIR / "check_version_consistency.py"
)
assert _spec is not None and _spec.loader is not None
cvc = importlib.util.module_from_spec(_spec)
# @dataclass は解決時に sys.modules[cls.__module__] を引くため、exec_module の前に
# 登録しておかないと AttributeError になる。
sys.modules[_spec.name] = cvc
_spec.loader.exec_module(cvc)


def _write_changelog(
    root: Path, entries: Sequence[tuple[str, str | None]] = (("1.2.3", "2026-08-04"),)
) -> None:
    """`entries` の順に version 見出しを並べた CHANGELOG.md を作る。

    日付に `None` を渡すと `## [x.y.z]` (日付なし) になる。`## [Unreleased]` の
    ような非リリース節も同じ経路で書ける (D7 で新設予定のため前方互換を試験する)。
    Keep a Changelog の慣行どおり **新しい順** に並べる。
    """
    parts = [
        "# Changelog\n\nAll notable changes to this project will be documented in this file.\n"
    ]
    for version, date in entries:
        heading = f"## [{version}]" if date is None else f"## [{version}] - {date}"
        parts.append(f"{heading}\n\n### Added\n\n- {version} の変更点\n")
    (root / "CHANGELOG.md").write_text("\n".join(parts), encoding="utf-8")


def _write_synthetic_repo(root: Path, version: str = "1.2.3") -> None:
    """全バージョン保持箇所が `version` で一致した合成 repo を作る。"""
    (root / "gui" / "src-tauri").mkdir(parents=True, exist_ok=True)
    # CHANGELOG は `--tag` 指定時にだけ読まれる。直前リリース (1.2.2) を置いて
    # バンプ方向チェックが「前より新しい」を満たす状態を既定にする。
    _write_changelog(root, ((version, "2026-08-04"), ("1.2.2", "2026-07-01")))

    (root / "pyproject.toml").write_text(
        f'[project]\nname = "allaganeye"\nversion = "{version}"\n', encoding="utf-8"
    )
    (root / "gui" / "src-tauri" / "Cargo.toml").write_text(
        f'[package]\nname = "allaganeye-gui"\nversion = "{version}"\nedition = "2021"\n',
        encoding="utf-8",
    )
    (root / "gui" / "package.json").write_text(
        json.dumps({"name": "allaganeye-gui", "version": version}), encoding="utf-8"
    )
    (root / "gui" / "package-lock.json").write_text(
        json.dumps(
            {
                "name": "allaganeye-gui",
                "version": version,
                "packages": {"": {"name": "allaganeye-gui", "version": version}},
            }
        ),
        encoding="utf-8",
    )
    (root / "gui" / "src-tauri" / "tauri.conf.json").write_text(
        json.dumps({"productName": "allaganeye-gui", "version": version}),
        encoding="utf-8",
    )
    # Cargo.lock は実物の構造を再現する。落とし穴が 2 つあるため:
    #   1. root 直下の `version = 4` は lockfile フォーマット版であってリリース
    #      バージョンではない
    #   2. 依存クレートも `[[package]]` として同じ形で並ぶ (ここでは serde 1.0.0)
    # どちらも拾ってはいけない。
    (root / "gui" / "src-tauri" / "Cargo.lock").write_text(
        "# This file is automatically @generated by Cargo.\n"
        "version = 4\n"
        "\n"
        '[[package]]\nname = "serde"\nversion = "1.0.0"\n'
        'source = "registry+https://github.com/rust-lang/crates.io-index"\n'
        "\n"
        f'[[package]]\nname = "allaganeye-gui"\nversion = "{version}"\n'
        'dependencies = [\n "serde",\n]\n',
        encoding="utf-8",
    )


def _error_lines(captured: str) -> list[str]:
    """`::error::` 注釈行だけを抜き出す。

    スクリプトは常に全箇所の一覧を stdout に出すため、出力全体に対して path の
    存在を assert すると「ガードが発火していなくても通る」vacuous green になる。
    発火の証拠は `::error::` 行に限定して観測する。
    """
    return [line for line in captured.splitlines() if line.startswith("::error::")]


def _versions_in(captured: str, path: str) -> list[str]:
    """一覧行 (`<path> (<field>): <version>`) から `path` 由来の値だけを抜き出す。"""
    return [
        line.rsplit(": ", 1)[1]
        for line in captured.splitlines()
        if line.startswith(f"{path} (")
    ]


def _set_version_at(root: Path, location: Any, version: str) -> None:
    """`location` が指す箇所のバージョンだけを差し替える。

    `cvc` は importlib で動的ロードした module なので `VersionLocation` を静的型と
    しては参照できない。型は `Any` にし、実体の検査は実行時の `isinstance` で行う。
    """
    assert isinstance(location, cvc.VersionLocation)
    path = root / location.path
    if location.fmt == "json":
        data = json.loads(path.read_text(encoding="utf-8"))
        for keys in location.keys:
            node = data
            for key in keys[:-1]:
                node = node[key]
            node[keys[-1]] = version
        path.write_text(json.dumps(data), encoding="utf-8")
    elif location.select is not None:
        # Cargo.lock は該当 [[package]] ブロックの version 行だけを差し替える
        # (root の `version = 4` や依存クレートの version を巻き込まない)。
        _, field, expected = location.select
        text = path.read_text(encoding="utf-8")
        text, replaced = re.subn(
            rf'(^{field} = "{re.escape(expected)}"\n)version = ".*"$',
            rf'\g<1>version = "{version}"',
            text,
            flags=re.M,
        )
        assert replaced == 1, (
            f"{location.path}: 差し替え対象が {replaced} 件 (1 件のはず)"
        )
        path.write_text(text, encoding="utf-8")
    else:
        text = path.read_text(encoding="utf-8")
        path.write_text(
            re.sub(r'^version = ".*"$', f'version = "{version}"', text, flags=re.M),
            encoding="utf-8",
        )


# --------------------------------------------------------------------------
# 正常系
# --------------------------------------------------------------------------


def test_all_locations_agree_returns_0(tmp_path: Path) -> None:
    _write_synthetic_repo(tmp_path, "1.2.3")
    assert cvc.main(["--repo-root", str(tmp_path)]) == 0


def test_matching_tag_returns_0(tmp_path: Path) -> None:
    _write_synthetic_repo(tmp_path, "1.2.3")
    assert cvc.main(["--repo-root", str(tmp_path), "--tag", "v1.2.3"]) == 0


# --------------------------------------------------------------------------
# 発火実証: 箇所ごとに 1 つずつズラす
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "location", cvc.VERSION_LOCATIONS, ids=[loc.path for loc in cvc.VERSION_LOCATIONS]
)
def test_each_location_mismatch_returns_1(
    tmp_path: Path, location: Any, capsys: pytest.CaptureFixture[str]
) -> None:
    """全箇所のいずれか 1 つがズレただけで exit 1 になること (箇所ごとの発火実証)。

    `::error::` 行のうち **注入した値 9.9.9 を報告している行** に当該 path が
    含まれることまで検査する (単に path が出力に現れるだけでは発火の証拠にならない)。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")
    _set_version_at(tmp_path, location, "9.9.9")

    rc = cvc.main(["--repo-root", str(tmp_path)])
    errors = _error_lines(capsys.readouterr().out)

    assert rc == 1
    assert isinstance(location, cvc.VersionLocation)
    offending = [line for line in errors if '"9.9.9"' in line]
    assert offending, f"注入した 9.9.9 を報告する ::error:: 行がない: {errors}"
    assert all(location.path in line for line in offending)


def test_package_lock_nested_field_mismatch_returns_1(tmp_path: Path) -> None:
    """package-lock.json の `packages[""].version` だけのズレも検知すること。

    npm は root `version` と `packages[""].version` の双方を持つため、片方だけが
    古びる drift が実在する。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")
    lock = tmp_path / "gui" / "package-lock.json"
    data = json.loads(lock.read_text(encoding="utf-8"))
    data["packages"][""]["version"] = "9.9.9"
    lock.write_text(json.dumps(data), encoding="utf-8")

    assert cvc.main(["--repo-root", str(tmp_path)]) == 1


def test_cargo_lock_ignores_lockfile_format_and_dependency_versions(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Cargo.lock は allaganeye-gui の `[[package]]` だけを見ること。

    素朴に「`version = ` 行」を拾う実装だと、root の lockfile フォーマット版
    (`version = 4`) や依存クレートの version (serde 1.0.0) を掴んでしまい、
    バンプしていないのに毎回 fail する / あるいは無関係な値で比較する。
    合成 repo は両方を仕込んであるので、ここが 0 で通ること自体が証拠になる。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")

    assert cvc.main(["--repo-root", str(tmp_path)]) == 0

    out = capsys.readouterr().out
    assert "gui/src-tauri/Cargo.lock" in out
    assert "4" not in _versions_in(out, "gui/src-tauri/Cargo.lock")
    assert _versions_in(out, "gui/src-tauri/Cargo.lock") == ["1.2.3"]


def test_cargo_lock_missing_package_entry_returns_2(tmp_path: Path) -> None:
    """パッケージ名が変わって `[[package]]` を特定できないときは exit 2 に倒すこと。

    「見つからないので検査しない」を 0 で通すと、ガードが無いより有害になる。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")
    lock = tmp_path / "gui" / "src-tauri" / "Cargo.lock"
    lock.write_text(
        lock.read_text(encoding="utf-8").replace(
            'name = "allaganeye-gui"', 'name = "allaganeye-gui-renamed"'
        ),
        encoding="utf-8",
    )

    assert cvc.main(["--repo-root", str(tmp_path)]) == 2


def test_tag_mismatch_returns_1(tmp_path: Path) -> None:
    """全箇所が一致していても tag とズレていれば fail すること。"""
    _write_synthetic_repo(tmp_path, "1.2.3")
    assert cvc.main(["--repo-root", str(tmp_path), "--tag", "v9.9.9"]) == 1


def test_mismatch_reports_every_offending_location(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """複数箇所がズレたとき、最初の 1 件で打ち切らず全件報告すること。"""
    _write_synthetic_repo(tmp_path, "1.2.3")
    _set_version_at(tmp_path, cvc.VERSION_LOCATIONS[1], "9.9.9")
    _set_version_at(tmp_path, cvc.VERSION_LOCATIONS[2], "8.8.8")

    rc = cvc.main(["--repo-root", str(tmp_path)])
    errors = _error_lines(capsys.readouterr().out)

    assert rc == 1
    assert any(
        '"9.9.9"' in line and cvc.VERSION_LOCATIONS[1].path in line for line in errors
    )
    assert any(
        '"8.8.8"' in line and cvc.VERSION_LOCATIONS[2].path in line for line in errors
    )


# --------------------------------------------------------------------------
# 構造エラー (検査の自己崩壊を green で通さない)
# --------------------------------------------------------------------------


def test_missing_file_returns_2(tmp_path: Path) -> None:
    _write_synthetic_repo(tmp_path, "1.2.3")
    (tmp_path / cvc.VERSION_LOCATIONS[0].path).unlink()
    assert cvc.main(["--repo-root", str(tmp_path)]) == 2


def test_missing_field_returns_2(tmp_path: Path) -> None:
    _write_synthetic_repo(tmp_path, "1.2.3")
    pkg = tmp_path / "gui" / "package.json"
    pkg.write_text(json.dumps({"name": "allaganeye-gui"}), encoding="utf-8")
    assert cvc.main(["--repo-root", str(tmp_path)]) == 2


def test_unparseable_file_returns_2(tmp_path: Path) -> None:
    _write_synthetic_repo(tmp_path, "1.2.3")
    (tmp_path / "gui" / "package.json").write_text("{ not json", encoding="utf-8")
    assert cvc.main(["--repo-root", str(tmp_path)]) == 2


# --------------------------------------------------------------------------
# --list-paths (バンプ時の stage 対象を機械的に得る)
# --------------------------------------------------------------------------


def test_list_paths_emits_deduped_paths(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """`git add --` に直接渡せる形 (1 行 1 path、重複なし) で出ること。

    `package-lock.json` は 2 フィールドを持つが stage 単位はファイルなので、
    path としては 1 個に畳まれていなければならない。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")

    rc = cvc.main(["--repo-root", str(tmp_path), "--list-paths"])
    lines = capsys.readouterr().out.splitlines()

    assert rc == 0
    assert lines == list(dict.fromkeys(loc.path for loc in cvc.VERSION_LOCATIONS))
    assert len(lines) == len(set(lines))


def test_list_paths_emits_lf_only() -> None:
    """改行が LF 固定であること (Windows の CRLF を出さない)。

    出力は `git add -- $(python ... --list-paths)` で機械消費される。Windows の
    text-mode stdout は "\\n" を CRLF へ変換するが、bash の既定 IFS は "\\r" を
    区切りに含めないため path 末尾に "\\r" が残り `git add` が exit 128 で落ちる
    (empirical-prompt-tuning iteration 5 の実測)。

    `capsys` は改行変換を挟まないので捕捉できない。実際に subprocess で起動して
    **生バイト列**を見る必要がある。
    """
    result = subprocess.run(
        [
            sys.executable,
            str(SCRIPTS_DIR / "check_version_consistency.py"),
            "--list-paths",
        ],
        capture_output=True,
        check=True,
    )
    assert b"\r" not in result.stdout
    assert result.stdout.decode("utf-8").splitlines() == list(
        dict.fromkeys(location.path for location in cvc.VERSION_LOCATIONS)
    )


def test_list_paths_does_not_read_files(tmp_path: Path) -> None:
    """バージョン値を読まずに path だけ返すこと。

    バンプ途中 (= まだ全箇所が一致していない状態) で stage 対象を得るための
    mode なので、不一致や欠損があっても path 一覧は返せなければ意味がない。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")
    (tmp_path / cvc.VERSION_LOCATIONS[0].path).unlink()

    assert cvc.main(["--repo-root", str(tmp_path), "--list-paths"]) == 0


# --------------------------------------------------------------------------
# 実 repo に対する pin test / doc 突合
# --------------------------------------------------------------------------


def test_real_repo_versions_are_consistent() -> None:
    """現在の repo の全バージョン保持箇所が一致していること (恒久 gate)。"""
    assert cvc.main(["--repo-root", str(REPO_ROOT)]) == 0


def _read_versioning_doc() -> str:
    return (REPO_ROOT / "docs" / "versioning.md").read_text(encoding="utf-8")


def _documented_fields(doc: str) -> set[tuple[str, str]]:
    """`docs/versioning.md` の表から `(ファイル, フィールド)` 対を抜く。

    フィールド列には 1 セルに複数フィールドが載る行がある
    (`gui/package-lock.json` の `version` と `packages[""].version`)。
    セル内の backtick 付きトークンを**全部**拾うことで、
    「ファイルは載っているがフィールドが 1 つ抜けた」drift を検出可能にする。
    """
    section = doc.split("## バージョン管理場所", 1)[1].split("\n## ", 1)[0]

    documented: set[tuple[str, str]] = set()
    for line in section.splitlines():
        if not line.startswith("| `"):
            continue
        # 消費経路 (3 列目) にも backtick があるので、セルに分けて 2 列目だけ見る
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        path_match = re.match(r"`([^`]+)`", cells[0])
        assert path_match is not None, f"ファイル列を読めません: {line}"
        for field in re.findall(r"`([^`]+)`", cells[1]):
            documented.add((path_match.group(1), field))
    return documented


def _guarded_fields() -> set[tuple[str, str]]:
    return {
        (location.path, cvc.field_label(location, keys))
        for location in cvc.VERSION_LOCATIONS
        for keys in location.keys
    }


def test_versioning_doc_lists_exactly_the_guarded_locations() -> None:
    """`docs/versioning.md` の一覧と `VERSION_LOCATIONS` が**フィールド単位**で一致すること。

    #911 の root cause は「doc が 3 箇所と宣言している間に実態が 5 箇所へ増えていた」
    こと。doc 側の一覧が silent に古びる経路を塞ぐ。

    ファイル単位で照合すると、`gui/package-lock.json` のように 1 ファイルが
    2 フィールドを持つ箇所で「ファイルは載っているが片方のフィールドが抜けた」
    drift を素通しする。#911 が潰したい drift そのものなのでフィールド単位で見る。
    """
    documented = _documented_fields(_read_versioning_doc())
    guarded = _guarded_fields()

    assert documented == guarded, (
        f"docs/versioning.md と VERSION_LOCATIONS が乖離: "
        f"doc のみ={documented - guarded} / script のみ={guarded - documented}"
    )


@pytest.mark.parametrize(
    ("description", "old", "new"),
    [
        (
            "同じファイルは載ったままフィールドが 1 つ消える",
            '`version` と `packages[""].version` の**両方**',
            "`version`",
        ),
        (
            "Cargo.lock の selector が別クレートを指す",
            "package[name=allaganeye-gui].version",
            "package[name=some-other-crate].version",
        ),
        (
            "フィールドの key path が浅くなる",
            "`project.version`",
            "`version`",
        ),
    ],
)
def test_doc_parity_detects_field_level_drift(
    description: str, old: str, new: str
) -> None:
    """doc 突合が**フィールド単位で発火する**ことの実証 (発火する側の検証)。

    ファイル単位の照合だと 1 件目 (`packages[""].version` の欠落) と
    2 件目 (selector 誤り) は素通りする。ガードが不発でも green になる
    false-green を避けるため、実際に drift を注入して不一致を観測する。
    """
    doc = _read_versioning_doc()
    drifted = doc.replace(old, new)
    assert drifted != doc, f"注入文字列が doc に存在しません ({description}): {old!r}"

    assert _documented_fields(drifted) != _guarded_fields(), (
        f"フィールド単位の drift を検出できていません: {description}"
    )


# --------------------------------------------------------------------------
# CHANGELOG 見出し日付 (#948)
#
# 本ガードは **Track D のタグ push で初めて発火する**。v0.3.1 開発中に自然発火する
# 機会が無いので、ここで赤 (発火) と緑 (false-red が出ない) の**両方**を注入で観測する。
# 「書いて緑」で終わらせるとリリース当日に直列最後の PR が止まる (spec 8.1 R-2)。
# --------------------------------------------------------------------------


def _prepare(
    root: Path,
    version: str,
    heading_date: str | None,
    previous: tuple[str, str | None] = ("0.0.1", "2020-01-01"),
) -> None:
    """`version` で全箇所一致 + 指定した見出し日付を持つ合成 repo を作る。"""
    _write_synthetic_repo(root, version)
    _write_changelog(root, ((version, heading_date), previous))


def test_matching_changelog_date_returns_0(tmp_path: Path) -> None:
    _prepare(tmp_path, "1.2.3", "2026-08-04")
    assert (
        cvc.main(
            [
                "--repo-root",
                str(tmp_path),
                "--tag",
                "v1.2.3",
                "--changelog-date-from",
                "2026-08-04T11:42:17+09:00",
            ]
        )
        == 0
    )


def test_wrong_changelog_date_returns_1(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """偽の日付を注入して **exit code の生値**で非ゼロを観測する (受け入れゲート)。"""
    _prepare(tmp_path, "1.2.3", "2026-08-01")

    rc = cvc.main(
        [
            "--repo-root",
            str(tmp_path),
            "--tag",
            "v1.2.3",
            "--changelog-date-from",
            "2026-08-04T11:42:17+09:00",
        ]
    )
    errors = _error_lines(capsys.readouterr().out)

    assert rc == 1
    assert any("2026-08-01" in line and "2026-08-04" in line for line in errors), (
        f"見出し日付の不一致を報告する ::error:: 行がない: {errors}"
    )


# 過去タグの実データ。**4 タグ中 2 件で JST 日付と UTC 日付が 1 日ずれる。**
# naive 実装 (UTC 素通し) は「utc_date が正しい」と判定するため、
#   * jst_date を期待する CHANGELOG に対して false-red を出し、
#   * utc_date を書いた CHANGELOG を誤って通す。
# 両方向を固定しないと、TZ 変換を消しても片側は緑のままになる。
_MIDNIGHT_JST_TAGS = [
    # (id, version, JST 表記, 同一瞬間の UTC 表記, JST 日付, UTC 日付)
    (
        "v0.1.1-0255JST",
        "0.1.1",
        "2026-04-20T02:55:19+09:00",
        "2026-04-19T17:55:19+00:00",
        "2026-04-20",
        "2026-04-19",
    ),
    (
        "v0.2.1-0843JST",
        "0.2.1",
        "2026-05-17T08:43:41+09:00",
        "2026-05-16T23:43:41+00:00",
        "2026-05-17",
        "2026-05-16",
    ),
]


@pytest.mark.parametrize(
    ("version", "jst_repr", "utc_repr", "jst_date", "utc_date"),
    [pytest.param(*row[1:], id=row[0]) for row in _MIDNIGHT_JST_TAGS],
)
@pytest.mark.parametrize("wire_format", ["jst", "utc"])
def test_jst_midnight_tag_does_not_false_red(
    tmp_path: Path,
    version: str,
    jst_repr: str,
    utc_repr: str,
    jst_date: str,
    utc_date: str,
    wire_format: str,
) -> None:
    """JST 深夜 (00:00-09:00 JST) のタグで false-red が出ないこと (緑側の実証)。

    同一瞬間を JST 表記で渡しても UTC 表記で渡しても、`Asia/Tokyo` へ明示変換した
    うえで比較するので **どちらも JST 日付に一致して 0** でなければならない。
    UTC 表記側が落ちるなら、それは runner の既定 TZ (UTC) を素通ししている証拠。
    """
    _prepare(tmp_path, version, jst_date, previous=("0.0.1", "2020-01-01"))
    reference = jst_repr if wire_format == "jst" else utc_repr

    assert (
        cvc.main(
            [
                "--repo-root",
                str(tmp_path),
                "--tag",
                f"v{version}",
                "--changelog-date-from",
                reference,
            ]
        )
        == 0
    ), f"JST 深夜タグで false-red ({version}, {wire_format} 表記)"


@pytest.mark.parametrize(
    ("version", "jst_repr", "utc_repr", "jst_date", "utc_date"),
    [pytest.param(*row[1:], id=row[0]) for row in _MIDNIGHT_JST_TAGS],
)
def test_jst_midnight_tag_rejects_utc_date(
    tmp_path: Path,
    version: str,
    jst_repr: str,
    utc_repr: str,
    jst_date: str,
    utc_date: str,
) -> None:
    """UTC 日付を書いた CHANGELOG は **落ちる** こと (赤側の実証)。

    naive 実装が「正しい」と判定する値をここで固定する。TZ 変換を外すと本テストが
    緑から赤へ反転するので、`test_jst_midnight_tag_does_not_false_red` と対になって
    実装が `Asia/Tokyo` を見ていることを両側から挟む。
    """
    _prepare(tmp_path, version, utc_date, previous=("0.0.1", "2020-01-01"))

    assert (
        cvc.main(
            [
                "--repo-root",
                str(tmp_path),
                "--tag",
                f"v{version}",
                "--changelog-date-from",
                jst_repr,
            ]
        )
        == 1
    ), f"UTC 日付 ({utc_date}) を通してしまった ({version})"


def test_hardcoded_timezone_is_asia_tokyo() -> None:
    """基準 TZ が `Asia/Tokyo` に固定されていること (規約と実装の突合)。"""
    assert cvc.CHANGELOG_TIMEZONE_NAME == "Asia/Tokyo"


def test_fixed_offset_matches_iana_asia_tokyo() -> None:
    """固定 +09:00 が IANA `Asia/Tokyo` と一致することを実データで突合する。

    実装が `zoneinfo` ではなく固定 offset を使うのは、Windows に IANA tz database
    が無く `ZoneInfo("Asia/Tokyo")` が `ZoneInfoNotFoundError` になるため
    (`scripts/check_version_consistency.py` の定数コメント参照)。その代償として
    「固定値が本当に Asia/Tokyo と同じか」を誰も見ない状態になるので、tz database
    が存在する環境 (CI の ubuntu) でだけ実タグ日時を使って突合する。
    """
    zoneinfo = pytest.importorskip("zoneinfo", reason="zoneinfo module unavailable")
    try:
        iana = zoneinfo.ZoneInfo("Asia/Tokyo")
    except zoneinfo.ZoneInfoNotFoundError:  # pragma: no cover - Windows 開発機
        pytest.skip("IANA tz database が無い環境 (Windows など)")

    from datetime import datetime as _datetime

    for _, _, jst_repr, utc_repr, jst_date, _ in _MIDNIGHT_JST_TAGS:
        for representation in (jst_repr, utc_repr):
            moment = _datetime.fromisoformat(representation)
            assert (
                moment.astimezone(cvc.CHANGELOG_TIMEZONE).date()
                == moment.astimezone(iana).date()
                == _datetime.strptime(jst_date, "%Y-%m-%d").date()
            ), f"固定 offset と IANA Asia/Tokyo が食い違う: {representation}"


def test_release_process_doc_documents_the_hardcoded_timezone() -> None:
    """`docs/release-process.md` が実装と同じ TZ を規約として明記していること。

    TZ は 1 箇所でも食い違うと 50% の確率で false-red になる値なので、doc 側が
    silent に古びる経路を塞ぐ (#911 の doc 突合と同じ処方)。
    """
    doc = (REPO_ROOT / "docs" / "release-process.md").read_text(encoding="utf-8")
    assert cvc.CHANGELOG_TIMEZONE_NAME in doc
    assert "タグを打つ日" in doc


def test_changelog_section_missing_returns_1(tmp_path: Path) -> None:
    """対象バージョンの節が無ければ落ちること。"""
    _write_synthetic_repo(tmp_path, "1.2.3")
    _write_changelog(tmp_path, (("1.2.2", "2026-07-01"),))

    assert cvc.main(["--repo-root", str(tmp_path), "--tag", "v1.2.3"]) == 1


def test_changelog_heading_without_date_returns_1(tmp_path: Path) -> None:
    """`--changelog-date-from` 無しでも「日付が無い」ことは検知すること。

    `--tag` 単独 (= `/release` の bump 時に手元で回す形) では値の一致までは見ないが、
    日付欄そのものの欠落は素通ししない。
    """
    _prepare(tmp_path, "1.2.3", None)

    assert cvc.main(["--repo-root", str(tmp_path), "--tag", "v1.2.3"]) == 1


def test_tag_without_reference_date_skips_value_comparison(tmp_path: Path) -> None:
    """`--tag` 単独では日付の**値**は見ない (バンプ日 != タグ日 の運用を壊さない)。"""
    _prepare(tmp_path, "1.2.3", "1999-12-31")

    assert cvc.main(["--repo-root", str(tmp_path), "--tag", "v1.2.3"]) == 0


def test_changelog_check_does_not_fire_without_tag(tmp_path: Path) -> None:
    """`--tag` 未指定時は CHANGELOG を一切読まないこと。

    CHANGELOG.md が存在しない合成 repo でも 0 で通ることが証拠になる。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")
    (tmp_path / "CHANGELOG.md").unlink()

    assert cvc.main(["--repo-root", str(tmp_path)]) == 0


def test_naive_reference_date_returns_2(tmp_path: Path) -> None:
    """offset を持たない ISO8601 は exit 2 (構造エラー) に倒すこと。

    naive な値を UTC / JST のどちらかとして**推測**すると、まさに潰したい
    「1 日ずれ」を検査側で再生産する。推測せずに落とす。
    """
    _prepare(tmp_path, "1.2.3", "2026-08-04")

    assert (
        cvc.main(
            [
                "--repo-root",
                str(tmp_path),
                "--tag",
                "v1.2.3",
                "--changelog-date-from",
                "2026-08-04T11:42:17",
            ]
        )
        == 2
    )


def test_unparseable_reference_date_returns_2(tmp_path: Path) -> None:
    _prepare(tmp_path, "1.2.3", "2026-08-04")

    assert (
        cvc.main(
            [
                "--repo-root",
                str(tmp_path),
                "--tag",
                "v1.2.3",
                "--changelog-date-from",
                "not-a-timestamp",
            ]
        )
        == 2
    )


def test_reference_date_without_tag_returns_2(tmp_path: Path) -> None:
    """`--changelog-date-from` だけ渡して `--tag` を忘れたら落とすこと。

    日付検査は `--tag` 指定時のみ発火する。基準日を渡しているのに検査が走らない
    組み合わせは **呼び出し側の配線ミス** なので、黙って 0 で通すと false-green
    になる (release.yml がこの形に退化しても気付けなくなる)。
    """
    _prepare(tmp_path, "1.2.3", "2026-08-04")

    assert (
        cvc.main(
            [
                "--repo-root",
                str(tmp_path),
                "--changelog-date-from",
                "2026-08-04T11:42:17+09:00",
            ]
        )
        == 2
    )


def test_unreleased_section_is_skipped(tmp_path: Path) -> None:
    """日付を持たない `## [Unreleased]` 節があっても通ること (D7 の前方互換)。

    PR-B2 が `## [Unreleased]` を新設する。非リリース節を version 見出しとして
    掴むと、日付欠落で恒久 red になるか、バンプ方向の比較対象を取り違える。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")
    _write_changelog(
        tmp_path,
        (("Unreleased", None), ("1.2.3", "2026-08-04"), ("1.2.2", "2026-07-01")),
    )

    assert (
        cvc.main(
            [
                "--repo-root",
                str(tmp_path),
                "--tag",
                "v1.2.3",
                "--changelog-date-from",
                "2026-08-04T00:10:00+09:00",
            ]
        )
        == 0
    )


# --------------------------------------------------------------------------
# バンプ方向 (ダウングレード検出、#918 item3)
# --------------------------------------------------------------------------


def test_downgrade_returns_1(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """直前のリリースより小さいバージョンを打とうとしたら落とすこと (発火実証)。

    #911 のガードは「7 フィールドが互いに一致し、タグとも一致する」しか見ないので、
    全箇所を揃えて v0.2.9 を打つとダウングレードでも全ゲートが緑になる。
    """
    _write_synthetic_repo(tmp_path, "0.2.9")
    _write_changelog(tmp_path, (("0.2.9", "2026-08-04"), ("0.3.0", "2026-08-01")))

    rc = cvc.main(["--repo-root", str(tmp_path), "--tag", "v0.2.9"])
    errors = _error_lines(capsys.readouterr().out)

    assert rc == 1
    assert any("0.3.0" in line and "0.2.9" in line for line in errors), (
        f"バンプ方向を報告する ::error:: 行がない: {errors}"
    )


def test_retagging_an_already_released_version_returns_1(tmp_path: Path) -> None:
    """リリース済みバージョンの打ち直しを落とすこと。

    「既存の最新リリースと同値」は CHANGELOG 上では**同じ版の節が 2 つある**形で
    しか現れない (自分自身を比較対象から外すため)。したがってこのケースは重複
    見出しとして捕まる。`_check_bump_direction` の `<=` が拾う経路ではない。
    """
    _write_synthetic_repo(tmp_path, "0.3.0")
    _write_changelog(tmp_path, (("0.3.0", "2026-08-04"), ("0.3.0", "2026-08-01")))

    assert cvc.main(["--repo-root", str(tmp_path), "--tag", "v0.3.0"]) == 1


def test_forward_bump_returns_0(tmp_path: Path) -> None:
    _write_synthetic_repo(tmp_path, "0.3.1")
    _write_changelog(tmp_path, (("0.3.1", "2026-08-04"), ("0.3.0", "2026-08-01")))

    assert cvc.main(["--repo-root", str(tmp_path), "--tag", "v0.3.1"]) == 0


def test_higher_version_with_malformed_date_is_still_compared(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """日付が壊れた上位版の節も比較対象に入ること (Codex medium finding)。

    見出しを「日付として読めた行」だけに絞ると `## [0.4.0] - TBD` が見出しとして
    存在しないことになり、0.4.0 が既にある CHANGELOG で v0.3.1 を打っても通る。
    ダウングレード検出は履歴ではなく見出しから証拠を採るので、無視した見出しが
    そのまま検出漏れになる。
    """
    _write_synthetic_repo(tmp_path, "0.3.1")
    _write_changelog(tmp_path, (("0.4.0", None), ("0.3.1", "2026-08-07")))
    # 日付欄が「無い」のではなく「壊れている」形にする。
    changelog = tmp_path / "CHANGELOG.md"
    changelog.write_text(
        changelog.read_text(encoding="utf-8").replace("## [0.4.0]", "## [0.4.0] - TBD"),
        encoding="utf-8",
    )

    rc = cvc.main(["--repo-root", str(tmp_path), "--tag", "v0.3.1"])
    errors = _error_lines(capsys.readouterr().out)

    assert rc == 1
    assert any("0.4.0" in line for line in errors), (
        f"日付が壊れた上位版 0.4.0 を見落とした: {errors}"
    )


def test_pre_release_heading_is_compared(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """pre-release 識別子付きの上位版も比較対象に入ること (Codex medium finding)。"""
    _write_synthetic_repo(tmp_path, "0.3.1")
    _write_changelog(tmp_path, (("0.4.0-rc1", "2026-08-01"), ("0.3.1", "2026-08-07")))

    rc = cvc.main(["--repo-root", str(tmp_path), "--tag", "v0.3.1"])
    errors = _error_lines(capsys.readouterr().out)

    assert rc == 1
    assert any("0.4.0-rc1" in line for line in errors), (
        f"pre-release の上位版を見落とした: {errors}"
    )


def test_release_after_its_own_pre_release_is_allowed(tmp_path: Path) -> None:
    """`0.4.0-rc1` がある状態で `v0.4.0` を打てること (false-red を出さない)。

    pre-release を「同 core の正式リリースと同値」にしてしまうと、rc を出した
    バージョンが二度と正式リリースできなくなる。
    """
    _write_synthetic_repo(tmp_path, "0.4.0")
    _write_changelog(
        tmp_path,
        (("0.4.0", "2026-09-01"), ("0.4.0-rc1", "2026-08-01"), ("0.3.1", "2026-08-07")),
    )

    assert cvc.main(["--repo-root", str(tmp_path), "--tag", "v0.4.0"]) == 0


def test_malformed_target_date_is_reported_distinctly(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """対象節の日付が壊れているとき「日付が無い」と区別して報告すること。

    リリース当日に「節はあるのに日付が無いと言われる」で原因探索の時間を使わない。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")
    _write_changelog(tmp_path, (("1.2.3", None), ("1.2.2", "2026-07-01")))
    changelog = tmp_path / "CHANGELOG.md"
    changelog.write_text(
        changelog.read_text(encoding="utf-8").replace(
            "## [1.2.3]", "## [1.2.3] - 2026-8-7"
        ),
        encoding="utf-8",
    )

    rc = cvc.main(["--repo-root", str(tmp_path), "--tag", "v1.2.3"])
    errors = _error_lines(capsys.readouterr().out)

    assert rc == 1
    assert any("2026-8-7" in line for line in errors), (
        f"壊れた日付文字列を報告していない: {errors}"
    )


def test_first_release_has_nothing_to_compare(tmp_path: Path) -> None:
    """比較対象が無い初回リリースは通ること。"""
    _write_synthetic_repo(tmp_path, "0.1.0")
    _write_changelog(tmp_path, (("0.1.0", "2026-04-17"),))

    assert cvc.main(["--repo-root", str(tmp_path), "--tag", "v0.1.0"]) == 0


def test_duplicate_version_headings_returns_1(tmp_path: Path) -> None:
    """同じバージョンの節が 2 つあるときは曖昧なので落とすこと。"""
    _write_synthetic_repo(tmp_path, "1.2.3")
    _write_changelog(
        tmp_path, (("1.2.3", "2026-08-04"), ("1.2.3", "2026-08-01"), ("1.2.2", None))
    )

    assert cvc.main(["--repo-root", str(tmp_path), "--tag", "v1.2.3"]) == 1


def test_crlf_changelog_is_handled(tmp_path: Path) -> None:
    """CRLF 改行の CHANGELOG.md でも見出しを取り違えないこと。

    本 repo は `core.autocrlf=true` の Windows 環境で開発されており、CHANGELOG.md は
    `.gitattributes` の `eol=lf` 対象**外**なので実際に CRLF で checkout される
    (実測)。一方 CI は Linux (LF) なので、**CRLF の取り扱いを壊しても CI は緑のまま
    開発機だけが落ちる**。ここでは改行をバイト列で書いて、プラットフォームに依らず
    CRLF 経路を通す (`Path.write_text` は既定で `\\n` を `os.linesep` へ変換するため、
    それ任せだと Linux 側で CRLF を 1 度も踏まない)。
    """
    _write_synthetic_repo(tmp_path, "1.2.3")
    (tmp_path / "CHANGELOG.md").write_bytes(
        "# Changelog\r\n"
        "\r\n"
        "## [1.2.3] - 2026-08-04\r\n"
        "\r\n"
        "- 新しい\r\n"
        "\r\n"
        "## [1.2.2] - 2026-07-01\r\n"
        "\r\n"
        "- 古い\r\n".encode()
    )

    assert (
        cvc.main(
            [
                "--repo-root",
                str(tmp_path),
                "--tag",
                "v1.2.3",
                "--changelog-date-from",
                "2026-08-04T11:42:17+09:00",
            ]
        )
        == 0
    )


def test_crlf_changelog_still_detects_wrong_date(tmp_path: Path) -> None:
    """CRLF でもガードが**発火する**こと (CRLF 経路が素通しになっていない)。"""
    _write_synthetic_repo(tmp_path, "1.2.3")
    (tmp_path / "CHANGELOG.md").write_bytes(
        b"# Changelog\r\n\r\n## [1.2.3] - 2026-08-01\r\n\r\n- x\r\n"
    )

    assert (
        cvc.main(
            [
                "--repo-root",
                str(tmp_path),
                "--tag",
                "v1.2.3",
                "--changelog-date-from",
                "2026-08-04T11:42:17+09:00",
            ]
        )
        == 1
    )


def test_missing_changelog_file_returns_2(tmp_path: Path) -> None:
    """CHANGELOG.md 自体が無いのは構造エラー (検査の自己崩壊) として 2 に倒すこと。"""
    _write_synthetic_repo(tmp_path, "1.2.3")
    (tmp_path / "CHANGELOG.md").unlink()

    assert cvc.main(["--repo-root", str(tmp_path), "--tag", "v1.2.3"]) == 2


# --------------------------------------------------------------------------
# 発火点の配線 (release.yml がガードを実際に呼んでいること)
# --------------------------------------------------------------------------


def _release_workflow() -> str:
    return (REPO_ROOT / ".github" / "workflows" / "release.yml").read_text(
        encoding="utf-8"
    )


def _release_workflow_effective() -> str:
    """`release.yml` から comment 行を除いた**実際に評価される**部分だけを返す。

    comment を含めて検査すると両方向に壊れる:

    * 肯定側 (`--changelog-date-from` があること) — comment 内に語があるだけで
      通ってしまい、呼び出しが消えても気付けない
    * 否定側 (`head_commit` が無いこと) — 「なぜ使わないか」を comment で説明
      した瞬間に落ちる

    どちらも「語の有無」ではなく「実効行の有無」を見れば解決する。
    """
    return "\n".join(
        line
        for line in _release_workflow().splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    )


def test_release_workflow_passes_reference_date_on_tag_push() -> None:
    """`release.yml` が `--tag` と一緒に `--changelog-date-from` を渡していること。

    日付検査は基準日を渡された時だけ値を比較する。workflow が渡さなくなると
    スクリプト側の test は全部緑のまま **CI では構造チェックしか走らない** という
    false-green になるので、呼び出し口を pin する (G1-1 3 点セットの 1 番目「発火点」)。
    """
    workflow = _release_workflow_effective()
    assert "--changelog-date-from" in workflow
    # 基準日は annotated tag の taggerdate のみ。
    assert "taggerdate" in workflow


def test_release_workflow_does_not_fall_back_to_commit_timestamp() -> None:
    """基準日を `head_commit.timestamp` へ落とさないこと (Codex high finding)。

    `head_commit.timestamp` は**タグが指す commit の日時**であってタグを打った
    日時ではない。commit とタグ push が日を跨ぐと規約とズレた日付を「正」として
    通してしまう。しかもそれが起きるのは lightweight tag を打った時 = 規約
    (`git tag -a`) 違反時だけなので、弱い基準で通すより落とす方が正しい。

    具体的な false-green: commit が 2026-08-06 23:00 JST、lightweight tag を
    2026-08-07 JST に push、CHANGELOG 見出しが `2026-08-06` — fallback があると
    これが通る。
    """
    assert "head_commit" not in _release_workflow_effective()


def test_release_workflow_still_triggers_on_constraints_change() -> None:
    """PR-A2 (#916) が入れた `constraints.txt` の paths を壊していないこと。"""
    assert "constraints.txt" in _release_workflow()
